### ISSUE TITLE
How about the performance after using it?

### ISSUE THREAD

**Issue by BoheSama1999** [zhaodice/qemu-anti-detection#71]
How about the performance after using it?

**Comment by zhaodice** [comment]
you can get 80% CPU performance and 98% GPU performance by passthough

**Comment by Samuil1337** [comment]
Moew~, don't think I didn't see your starred repos.
VirtIO is completely out of the question, because QEMU is hidden well enough that the guest driver won't be able to detect the virtual hardware. Using emulated hardware will be slower and cause quite a bit of CPU overhead, so the best solution would be passing through as much as possible: GPU, peripherals, NVMe. The only thing I wouldn't pass through is the complete network card for security reasons. If you have this specific hardware setup, you wouldn't feel any performance difference.

**Comment by BoheSama1999** [comment]
meow～
Thank you for your answer. I passed through my USB controller, GPU, and used SRIOV to pass through the network card. I pined the CPU then isolated the CPU core, passed disk and Bluetooth. However, I felt that the most obvious issue was the severe decline in memory performance. I tried using hugepage, and although the performance did improve significantly, the difference was still a bit obvious compared to the physical machine. I realized that the default hugepage size was only 2M per chunk, so I set it to 1Gx18 in the kernel cmd in grub. When I played the game again, its frame rate improved significantly, only about 10fps less than the host machine

**Comment by Samuil1337** [comment]
Oh wow. That's a real machine with extra steps. I actually don't think that RAM performance is that bad without static hugepages. Did you benchmark memory inside the VM in any way, so you can prove that it's worth the loss of RAM capacity on the host?

**Comment by BoheSama1999** [comment]
> Oh wow. That's a real machine with extra steps. I actually don't think that RAM performance is that bad without static hugepages. Did you benchmark memory inside the VM in any way, so you can prove that it's worth the loss of RAM capacity on the host?

I checked the memory and cache benchmark of AIDA64. Whether it is set with static hugepages or not, the gap in the data is not very obvious. But I found a problem that seems to be serious. Regardless of whether 1Ghugepages is used or not, it shows that the memory cache performance of the guest machine is significantly lower than the host performance. The data shows that the read, write and copy of the speed of memory are ten times different from the host, and the latency is more than 10 times. From the perspective of CPU cache performance, it seems that the cpu cache performance of guest machines is not very optimistic, the cache performance is dozens of times different, and the latency is the same . 

### _Here about the benchmark result_ 
**Neofetch**
![image](https://github.com/zhaodice/qemu-anti-detection/assets/153600213/38a2c711-70d7-4a13-bb0a-c71632b4c35d)

**Hardware infomations**
[Link](https://pastebin.com/Re3XN16t)

**1.Host test**
![cachemem](https://github.com/zhaodice/qemu-anti-detection/assets/153600213/2ddcb804-998d-49a0-ace6-1a45b31d1511)

**2.Guest without 1GstaticHugepages**  # 9Cores for Guest,1Core for Host
![b](https://github.com/zhaodice/qemu-anti-detection/assets/153600213/6875ab1e-ead3-43a7-b57d-cd8069c5844b)
**The xml : [Link](https://pastebin.com/YKqVF4hw)**

**3.Guest with 1GstaticHugepages**  # 9Cores for Guest,1Core for Host
![a](https://github.com/zhaodice/qemu-anti-detection/assets/153600213/10be0cee-2a6c-453f-8842-0b7fffcb7431)
**The xml :  [Link](https://pastebin.com/vgpCMq1B)**

**Comment by Samuil1337** [comment]
Oh wow that's interesting. Thanks for the info

**Comment by Samuil1337** [comment]
I actually tested transparent huge pages (2 MiB each) against static ones (1 GiB) on my AMD Ryzen 7 3700x. 

**THP**
![transparent_hugepages](https://github.com/zhaodice/qemu-anti-detection/assets/130246533/0d2ab898-2ddc-463b-93e2-392a3af6091b)

**SHP**
![static_hugepages](https://github.com/zhaodice/qemu-anti-detection/assets/130246533/6a96b005-9e13-4138-a331-496de5527308)

The statically allocated pages were almost as fast, but had half a nano second less latency. Both results are not scientific at all because I ran the tests only once on free AIDA. However, they do align with [Red Hat's benchmarks](https://developers.redhat.com/blog/2021/04/27/benchmarking-transparent-versus-1gib-static-huge-page-performance-in-linux-virtual-machines#benchmarks) which have shown a 2% performance increase with 1 GiB SHP and prove that in my case it is not worth the lost RAM on the host.
Something about your test results is weird though. The caches of your CPU, which came out 2 years after mine, are extremely slow; compared to your real hardware and especially my VM. Try adding `<cache mode="passthrough"/>` to the CPU section and double-check your CPU pinning. Please post your output of `lscpu -e`, so I can look over it too.
